version: '3.8'
services:
 dynamodb-local:
   container_name: dynamodb-local
   image: "amazon/dynamodb-local:latest"
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal  
   ports:
     - "9000:8000"